---
title: "Assignment 1"
author: "PD, JO, and MvD, group 06"
date: "17 febuary 2023"
output: pdf_document
highlight: tango
---

## Exercise 1
Here is the part for exercise 1
**a)**
```{r}
# what is code without comments
print("exercise 1.a code here!")

```

## Exercise 2
Here is the part for exercise 2
**a)**
```{r}
# what is code without comments
print("exercise 2.a code here!")

fat = scan("../datasets/cholesterol.txt", what = list(before = 0, after = 0))

#a
boxplot(fat)
attach(fat)

par(mfrow = c(1,2))
hist(before)
hist(after)

par(mfrow = c(1,2))
qqnorm(before)
qqnorm(after)

plot(before~after)

cor.test(before, after)
cor.test(before, after, method="spearman")

``` 
**b)**
```{r}

t.test(before, after, paired = TRUE) # are the samples paired? yes

permStat = function(x, y) { mean(x-y) }

B = 1000; tstar=numeric(B);
i =0
for(i in i:B) { 
  cbind = cbind(before, after)
  fatStar = t(apply(cbind,1,sample))
  tstar[i] = permStat(fatStar[,1], fatStar[,2]) 
  }

t = permStat(before, after)
print(t)

hist(tstar, xlim = c(-0.6,0.6))
lines(rep(t,2), c(0,20), col = "lightblue", lwd=2)
p1=sum(tstar<t)/B
pr=sum(tstar>t)/B
p=2*min(p1,pr); p
#conclusion indeed significant difference

``` 
**c)**
```{r}
# bootstrap test to find out if fat$after is uniformly distributed. and construct a 95% confidence interval. (Kolmogorov-Smirnov?)


```




## Exercise 3
Here is the part for exercise 3
**a)**

```{r}
# what is code without comments
print("exercise 3.a code here!")

```


## Exercise 4
Here is the part for exercise 4
**a)**

```{r}
# what is code without comments
print("exercise 4.a code here!")

```